/**
 * Worker bindings (`Env`) and the Hono request context. `Variables` mirrors
 * exactly what the global middleware in `src/app.tsx` sets for handlers.
 */
import type { UserRow } from './db/types';
import type { Locale, TranslateFn } from './i18n';
import type { SiteSettings } from './lib/settings';

export interface Env {
  DB: D1Database;
  KV: KVNamespace;
  ASSETS: Fetcher;

  APP_NAME?: string;
  APP_URL?: string;

  /** Base URL (up to but excluding the hash) for Gravatar avatars. */
  GRAVATAR_MIRROR?: string;

  SESSION_PEPPER?: string;

  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;

  MAILER_DRIVER?: string;
  SMTP_HOST?: string;
  SMTP_PORT?: string;
  SMTP_SECURE?: string;
  SMTP_USER?: string;
  SMTP_PASSWORD?: string;
  SMTP_FROM?: string;

  ADMIN_EMAILS?: string;
}

export interface Variables {
  user?: UserRow | null;
  sessionToken?: string;
  csrfToken: string;
  /** Per-request CSP nonce, generated by `secureHeaders` (see src/app.tsx). */
  secureHeadersNonce?: string;
  locale: Locale;
  t: TranslateFn;
  settings: SiteSettings;
  appName: string;
  isAdmin: boolean;
}

export type AppContext = {
  Bindings: Env;
  Variables: Variables;
};
